#mengambil inputan
print("nama lengkap saya:")
namalengkap=input("")
print("nama panggilan saya:")
namapanggilan=input("")
print ("Nomor NPM saya:")
npm=int(input())
print("tanggal lahir saya:")
tempatlahir=input("")
print("umur saya:")
umur=int(input())
print("alamat saya:")
alamat=input("")
print ("No HPsaya:")
telepon=input()
